### ISSUE TITLE
Storing an object with MongoDB ObjectId() converts to String

### ISSUE THREAD

**Issue by petr-inmite** [mrvautin/adminMongo#44] opened 2016-02-25 21:45 UTC
I spent quite a some time on this one...

If you create an object in MongoDB, the "_id" is of ObjectId type. Of you open and save the document in MongoAdmin, however, the value is converted to String and cannot be used for comparison elsewhere.

**Comment by mrvautin** [comment] 2016-02-25 21:50
This is a duplicate of open issue #31.

**Closed by mrvautin** 2016-02-25 21:50 UTC
