### ISSUE TITLE
Incorrect JSON valiue escaping

### ISSUE THREAD

**Issue by petr-inmite** [mrvautin/adminMongo#45] opened 2016-02-25 21:47 UTC
1) Create a document like this:

```
    {
        "_id": "ObjectId(\"1\")",
        "name": "Test"
    }
```
2) Try to open or delete the document.

=> Error, the value escaping does not work correctly.

**Comment by mrvautin** [comment] 2016-02-25 21:50
This is a duplicate of open issue #31.

**Closed by mrvautin** 2016-02-25 21:50 UTC
