### ISSUE TITLE
Is there a way to add a basic-auth login screen? 

### ISSUE THREAD

**Issue by menocreativity** [mrvautin/adminMongo#10] opened 2016-01-29 11:45 UTC
I'm hosting adminMongo on a server and I'm looking to add some kind of password protection to it (as currently anybody with the URL can actually access the UI). Is there anything we can do to add a basic auth? 

I went through the readme but didn't see anything about admin-login credentials for the UI. (Or I must have overlooked it).

**Comment by menocreativity** [comment] 2016-01-29 12:08
Went through the source but wasn't able to find any references. Implemented a basicAuth version myself based on this article. It's nothing fancy but it does the job of locking AdminMongo down.

Based on this article: https://davidbeath.com/posts/expressjs-40-basicauth.html

I added an auth object to the app.json config file:
```
{
	"app":{
		"host":"0.0.0.0",
		"port":"1234"
	},
	"auth": {
		"user": "secretUser",
		"password": "VerySecretPassword"
	}
}
```
... installed an additional dependency...

```
npm install basic-auth --save
```
... required it in the app.js...

```
var basicAuth = require('basic-auth');
```

...and implemented this...

```
app.use(function (req, res, next) {
    function unauthorized(res) {
        res.set('WWW-Authenticate', 'Basic realm=Authorization Required');
        return res.send(401);
    };

    var auth = basicAuth(req);

    if (!auth || !auth.name || !auth.pass) {
        return unauthorized(res);
    };

    if (auth.name === auth_user && auth.pass === auth_pass) {
        return next();
    } else {
        return unauthorized(res);
    };
});
```

Run the app: now you get a basic auth dialog that let's you in once you fulfill with the correct user/pass combo :)

**Comment by mrvautin** [comment] 2016-01-30 10:35
I see your have a working solution but I've been thinking about this since your raised the issue and I have a few concerns.

This app was designed to be run locally and most commands run against MongoDb are not sanitised at all. 

My concern is by adding this people might think that the app is now secure and can be run on a server, possibly even public facing. I don't think the app can be deemed secure by adding this and my concerns are people could get their MongoDb nuked and complain here.

Out of interest: what are your reasons for running on a server? Is it a local or public facing server?

**Comment by drakoumel** [comment] 2016-02-01 10:36
I wouldn't really suggest exposing this interface to public. 
However as I use it as an admin interface to look on the data stats, I have enforced the access to be only through localhost, blocked the port to the outside and have applied an htaccess password through apache. 

I could create a wiki if you need more help with the above measures.

**Comment by mrvautin** [comment] 2016-02-01 10:39
Do you agree that there shouldn't be a false sense of security by adding authentication to the application? 

Your method seem much more robust rather than moving towards making the application totally secure.

**Comment by drakoumel** [comment] 2016-02-01 10:56
@mrvautin yes I agree, if "we" would add security on an application level then we should handle more things rather than just a password.

By implementing my approach, you are protecting the application through the infrastructure and also keep the liability away from the app.

**Closed** 2016-02-02 23:24 UTC
